nyc_taxi_project:
  outputs:
    dev:
      project: dataengineer-463405
      dataset: nyctaxi
      threads: 10
      type: bigquery
      method: service-account
      keyfile: /home/ian/nyc_taxi_project/gcloudkeys.json
      location: africa-south1
    prod:
      project: dataengineer-463405
      dataset: nyctaxi
      threads: 10
      type: bigquery
      method: oauth
      location: africa-south1
  target: dev