substitutions:
  _REPO_NAME: '-'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'africa-south1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/dbt-on-cloud-run', '.' ]
images: [ 'africa-south1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/dbt-on-cloud-run' ]